# Generated by Django 4.1 on 2022-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snacks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snack",
            old_name="reviewer",
            new_name="purchaser",
        ),
        migrations.RemoveField(
            model_name="snack",
            name="rating",
        ),
        migrations.AddField(
            model_name="snack",
            name="description",
            field=models.TextField(default="description"),
            preserve_default=False,
        ),
    ]
